### ISSUE TITLE
Check out BlueBuild for building custom images

### ISSUE THREAD

**Issue by fiftydinar** [kg4vdk/arcos-linux#4]
Just accidentally stumbled upon this custom image when browsing on Reddit & I want to say that you may want to check this out.

[Blue-Build](https://blue-build.org/) tooling allows you to build custom images based on Fedora Atomic distributions in an easy & reliable way. More concretely, images are based on [Universal Blue](https://universal-blue.org/) base images, which include high quality fixes to Fedora Atomic like proprietary codecs, additional udev rules, automatic updates & similar.

It builds your custom image directly in GitHub Actions every day, so you get the daily updates from Fedora & any failed image build won't end up in your system!

Along with that, advantage is easy configuration of the build process with recipe.yml, which includes configuration for the base image, Fedora version, modules configuration & such. Modules are based on bash. They are easy to use, easy to maintain & some very useful functionality can be deployed, thanks to them.

Check out the project page & documentation for more details.

Unfortunately, Cinnamon image was unofficially offered by Universal Blue project, but due to low maintenance, it's abandoned.
So your closest base image that you could try to use is Universal Blue's Budgie I guess.

I don't know the rest of your OS build system, what is used, as only modules are here in GitHub, but I guess that you are used to Linux Mint & it's ecosystem, including the build system that you deploy for ArcOS, so this will maybe look like something completely new to you.

**Comment by kg4vdk** [comment]
Thanks for the intro to Blue-Build! However, there are no plans to rebase this project on Fedora.
